### ISSUE TITLE
在启动Mirai超过一段时间(通常是几天)后，偶尔会出现停止检测的现象

### ISSUE THREAD

**Issue by byx2020** [Colter23/bilibili-dynamic-mirai-plugin#13]
最近出现过几次这种情况，启动Mirai，可以正常运行、检测、推送，但是有几次放了一两天后，就再没看到过下图的绿色检测提示，同时订阅的UP更新也没在群内推送，不过重启Mirai就又恢复正常了。
![image](https://user-images.githubusercontent.com/58938653/118787018-fcd74800-b8c4-11eb-9fb1-aa302277a11a.png)
以下为插件运行环境信息(需要更多可以问我)：
操作系统：Windows Server 2012 R2
Mirai版本：2.2.2
插件版本：1.0.4
问题相关配置项：
```
dynamic: 
  enable: true
  interval: 20
  lowSpeed: '000-000'
  videoMode: false
  saveDynamicImage: true
```
